[package]
name = "chat_completions_streaming"
version = "0.1.0"
edition = "2021"

[dependencies]
ai = { path = "../../crates/ai" }
futures = "0.3.31"
serde_json = "1.0.137"
tokio = { version = "1.43.0", features = ["full"] }
