[package]
name = "ai"
version = "0.2.0"
edition = "2021"
authors = ["Prabir Shrestha <mail@prabir.me>"]
license = "MIT"
description = "AI"
repository = "https://github.com/prabirshrestha/ai"

[dependencies]
async-trait = "0.1.85"
derive_builder = "0.20.2"
dyn-clone = "1.0.17"
reqwest = "0.12.12"
serde = { version = "1.0.217", features = ["serde_derive"] }
thiserror = "2.0.9"
