[package]
name = "ai"
version = "0.2.0"
edition = "2021"
authors = ["Prabir Shrestha <mail@prabir.me>"]
license = "MIT"
description = "AI"
repository = "https://github.com/prabirshrestha/ai"

[dependencies]
