[package]
name = "ai"
version = "0.2.1"
edition = "2021"
authors = ["Prabir Shrestha <mail@prabir.me>"]
license = "MIT"
description = "AI"
repository = "https://github.com/prabirshrestha/ai"
readme = "../../README.md"

[dependencies]
async-trait = "0.1.85"
derive_builder = "0.20.2"
dyn-clone = "1.0.17"
reqwest = { version = "0.12.12", features = ["json"], default-features = false }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
serde_json = "1.0.135"
thiserror = "2.0.9"
time = { version = "0.3.37", features = ["parsing"] }

[dev-dependencies]
httpmock = "0.7.0"
tokio = { version = "1.43.0", features = ["rt-multi-thread"] }

[features]
default = ["ollama_client", "openai_client", "native_tls"]
ollama_client = []
openai_client = []
native_tls = ["reqwest/native-tls"]
rustls_tls = ["reqwest/rustls-tls"]
