[package]
name = "chat_completions_streaming_with_cancellation_token"
version = "0.1.0"
edition = "2021"

[dependencies]
ai = { path = "../../crates/ai" }
futures = "0.3.31"
tokio = { version = "1.43.0", features = ["full"] }
tokio-util = "0.7.13"
