name: CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build and Test
    env:
      # emit backtraces on panics.
      RUST_BACKTRACE: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Check code formatting
        run: cargo fmt --all -- --check

      - name: Build
        run: cargo build --all --locked --verbose

      - name: Run tests
        run: cargo test --all --verbose
